### ISSUE TITLE
Dbus-python is a depecrated module

### ISSUE THREAD

**Issue by rumourscape** [purusharthmalik/cowin-slot-availability#1]
Dbus-python is deprecated and is having errors installing.

**Comment by purusharthmalik** [comment]
What operating system are you trying to execute the program on?

**Comment by purusharthmalik** [comment]
As windows does not support dbus natively, you can follow [https://stackoverflow.com/questions/37506906/how-could-run-python-dbus-on-windows](url) this link to execute the program on windows.
